### ISSUE TITLE
Вылет игры при tas_strafe 1

### ISSUE THREAD

**Issue by Nyvyme** [r47t/Left4TAS#1]
Когда я прописываю **tas_strafe 1**, или происходит включение через скрипт, игра зависает на 1 секунду, а потом вылетает без ошибки.
Даже если у меня прописаны значения **tas_strafe_yaw** и **tas_strafe_buttons**, происходит вылет.

Версия лефты: **2.2.2.0**

**Comment by sw1ft747** [comment]
Хмм, я писал, в описании, что не буду поддерживать TLS версии, только версии 2.1.5.5 и ниже. Это муторно искать/обновлять сигнатуры с оффсетами для постоянного обновляющейся игры, да и в какой-то степени это бойкот самому TLS обновлению
