### ISSUE TITLE
Here is log when I load the plugin in L4D2, Left4TAS-1.1.0

### ISSUE THREAD

**Issue by 3918831** [r47t/Left4TAS#2]
It seems that the plugin is not loaded correctly.

Log:
] plugin_load left4tas
Loading unsigned module left4tas
Access to secure servers is disabled.
[L4TAS] VScriptServerInit failed initialization
[L4TAS] VScript functions are unavailable
[L4TAS] Host_NewGame failed initialization
[L4TAS] Engine functions are unavailable
[L4TAS] CBasePlayer::PlayerRunCommand failed initialization
[L4TAS] Server functions are unavailable
[L4TAS] CCSModeManager::Init failed initialization
[L4TAS] Client functions are unavailable
[L4TAS] VGUI functions are unavailable
[Left4TAS] Loaded with limited features
Loaded plugin "left4tas"
exec: couldn't exec left4tas/tas_plugin_load

] version
Version 2.1.5.5 (left4dead2)
Network Version 2.0.4.2
Exe build: 17:55:57 Feb  3 2015 (5764) (550)

No sourcemod installed and -insecure launch option used.

**Comment by sw1ft747** [comment]
Thanks, I've fixed incorrect signature
